-- ১. আগের টেবিলগুলো রিসেট করে নেওয়া
drop view if exists public.today_contributions;
drop table if exists public.contributions;
drop table if exists public.profiles;

-- ২. নতুন করে profiles টেবিল তৈরি (pin কলাম ও নিজস্ব uuid সহ)
create table public.profiles (
    id uuid primary key default gen_random_uuid(),
    username text unique not null,
    display_name text not null,
    pin text not null,
    role text not null default 'user' check(role in ('user','admin')),
    has_contributed boolean not null default false,
    created_at timestamptz not null default now()
);

-- ৩. contributions টেবিল তৈরি
create table public.contributions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    business_date date not null,
    amount integer not null check(amount in (10,20,30,50)),
    contribution_order integer not null,
    created_at timestamptz not null default now(),
    unique(user_id, business_date),
    unique(business_date, contribution_order)
);

-- ৪. ইউজার ও অ্যাডমিনদের ডেটা ইনসার্ট করা
INSERT INTO public.profiles (username, display_name, pin, role) VALUES
('Sayem', 'Sayem', '1234', 'user'),
('Ronok', 'Ronok', '2345', 'user'),
('Hridom', 'Hridom', '3456', 'user'),
('Hasib', 'Hasib', '4567', 'user'),
('Twha', 'Twha', '5678', 'user'),
('Akash', 'Akash', '6789', 'user'),
('Sourav', 'Sourav', '7890', 'user'),
('Shihab', 'Shihab', '8901', 'user'),
('admin', 'Admin', '20365', 'admin');